/**
 * Persistence: localStorage autosave and JSON file import/export.
 *
 * Only authored entities are persisted (Bubbles and Rails).
 * Feeders are regenerated by the solver on load.
 * User recipes are persisted separately by the recipe store.
 */

import type { Bubble, Rail, Tee } from '../scene/types'
import type { RecipeMap } from '../recipes/types'

const AUTOSAVE_KEY = 'factorio-plotter-diagram'

export interface DiagramJson {
  version: 1
  bubbles: Bubble[]
  rails: Rail[]
}

/**
 * Normalize a persisted rail to the current shape.
 *
 * Migrations performed:
 *  - Legacy `resourceType: string` → `resourceTypes: [string]`.
 *  - Legacy `bubbleOrigin` is dropped (rails are never anchored to bubbles).
 *  - Legacy `parametricOrigin: { parentRailId, t }` → `tee: { parentRailId,
 *    anchorEndIndex }` with `anchorEndIndex = t < 0.5 ? 0 : 1`. The legacy
 *    rail had `points[0]` overridden by the parent at render time, so the
 *    real free endpoint lived at `points[points.length - 1]`. The new shape
 *    expects `points[0]` to be the free endpoint and `points[1]` a
 *    ray-direction reference back toward the parent — so we swap order:
 *    `points = [legacy.last, legacy.first]`. (Resolver casts the ray from
 *    points[0] toward points[1].) For degenerate legacy rails with both
 *    points equal, the ray length is zero and the resolver falls back to the
 *    stored points; visually broken until the user re-tees, which is fine.
 */
interface LegacyParametricOrigin { parentRailId: string; t: number }
type LegacyRail = Rail & {
  resourceType?: string
  parametricOrigin?: LegacyParametricOrigin | null
}

function normalizeRail(r: LegacyRail): Rail {
  const resourceTypes = Array.isArray(r.resourceTypes) && r.resourceTypes.length > 0
    ? r.resourceTypes
    : r.resourceType
      ? [r.resourceType]
      : ['unknown']
  let points = r.points
  let tee: Tee | undefined = r.tee
  if (!tee && r.parametricOrigin) {
    const anchorEndIndex: 0 | 1 = r.parametricOrigin.t < 0.5 ? 0 : 1
    tee = { parentRailId: r.parametricOrigin.parentRailId, anchorEndIndex }
    if (points.length >= 2) {
      points = [points[points.length - 1], points[0]]
    }
  }
  return {
    id: r.id,
    resourceTypes,
    label: r.label,
    points,
    isSupply: r.isSupply ?? true,
    tee,
  }
}

/**
 * Old persisted bubble shape (pre-recipe-centric refactor).
 * productId + recipeVariantId + outputTarget → recipeId + outputBindings
 */
interface LegacyBubble {
  id: string
  position: { x: number; y: number }
  productId?: string
  recipeVariantId?: string | null
  outputTarget?: string | null
  recipeId?: string
  outputBindings?: Record<string, string | null>
  isPrivate?: boolean
}

/**
 * Normalize a persisted bubble to the current shape.
 *
 * Migration paths:
 * - Old shape (productId + recipeVariantId + outputTarget):
 *   → recipeId derived from productId + recipeVariantId via recipeMap lookup.
 *   → outputBindings backfilled as { [productId]: outputTarget ?? null }.
 * - New shape (recipeId + outputBindings): passed through as-is.
 * - Missing outputBindings: initialized to {}.
 */
function normalizeBubble(b: LegacyBubble, recipeMap: RecipeMap): Bubble {
  // New shape — already has recipeId
  if (b.recipeId) {
    return {
      id: b.id,
      position: b.position,
      recipeId: b.recipeId,
      isPrivate: b.isPrivate ?? false,
      outputBindings: b.outputBindings ?? {},
    }
  }

  // Old shape — derive recipeId from productId + recipeVariantId
  const productId = b.productId ?? 'unknown'
  const variantId = b.recipeVariantId ?? null

  // Look up recipe id: variantId === null or 'default' → productId; else product-variantId
  let recipeId: string
  if (!variantId || variantId === 'default') {
    recipeId = productId
  } else {
    recipeId = `${productId}-${variantId}`
  }

  // Verify the id exists in the map; if not, fall back to productId
  if (!recipeMap[recipeId]) {
    recipeId = productId
  }

  // Backfill outputBindings from single outputTarget
  const outputTarget = b.outputTarget ?? null
  const outputBindings: Record<string, string | null> = {
    [productId]: outputTarget,
  }

  return {
    id: b.id,
    position: b.position,
    recipeId,
    isPrivate: b.isPrivate ?? false,
    outputBindings,
  }
}

function normalizeDiagram(data: DiagramJson, recipeMap: RecipeMap): DiagramJson {
  return {
    ...data,
    bubbles: (data.bubbles ?? []).map(b => normalizeBubble(b as LegacyBubble, recipeMap)),
    rails: (data.rails ?? []).map(normalizeRail),
  }
}

// ============================================================
// Autosave
// ============================================================

export function autosave(bubbles: Record<string, Bubble>, rails: Record<string, Rail>): void {
  const data: DiagramJson = {
    version: 1,
    bubbles: Object.values(bubbles),
    rails: Object.values(rails),
  }
  try {
    localStorage.setItem(AUTOSAVE_KEY, JSON.stringify(data))
  } catch {
    // Storage full or unavailable — silently ignore
  }
}

export function loadAutosave(recipeMap: RecipeMap): DiagramJson | null {
  try {
    const raw = localStorage.getItem(AUTOSAVE_KEY)
    if (!raw) return null
    const data = JSON.parse(raw) as DiagramJson
    if (data.version !== 1) return null
    return normalizeDiagram(data, recipeMap)
  } catch {
    return null
  }
}

// ============================================================
// JSON file export
// ============================================================

export function exportDiagramJson(
  bubbles: Record<string, Bubble>,
  rails: Record<string, Rail>
): void {
  const data: DiagramJson = {
    version: 1,
    bubbles: Object.values(bubbles),
    rails: Object.values(rails),
  }
  const json = JSON.stringify(data, null, 2)
  const blob = new Blob([json], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = 'factorio-diagram.json'
  a.click()
  URL.revokeObjectURL(url)
}

// ============================================================
// JSON file import
// ============================================================

export function importDiagramJson(recipeMap: RecipeMap): Promise<DiagramJson | null> {
  return new Promise(resolve => {
    const input = document.createElement('input')
    input.type = 'file'
    input.accept = '.json,application/json'
    input.onchange = () => {
      const file = input.files?.[0]
      if (!file) {
        resolve(null)
        return
      }
      const reader = new FileReader()
      reader.onload = () => {
        try {
          const data = JSON.parse(reader.result as string) as DiagramJson
          if (data.version !== 1) {
            resolve(null)
            return
          }
          resolve(normalizeDiagram(data, recipeMap))
        } catch {
          resolve(null)
        }
      }
      reader.readAsText(file)
    }
    input.click()
  })
}
