/**
 * Persistence: localStorage autosave and JSON file import/export.
 *
 * Only authored entities are persisted (Bubbles and Rails).
 * Feeders are regenerated by the solver on load.
 * User recipes are persisted separately by the recipe store.
 */

import type { Bubble, Rail } from '../scene/types'

const AUTOSAVE_KEY = 'factorio-plotter-diagram'

export interface DiagramJson {
  version: 1
  bubbles: Bubble[]
  rails: Rail[]
}

// ============================================================
// Autosave
// ============================================================

export function autosave(bubbles: Record<string, Bubble>, rails: Record<string, Rail>): void {
  const data: DiagramJson = {
    version: 1,
    bubbles: Object.values(bubbles),
    rails: Object.values(rails),
  }
  try {
    localStorage.setItem(AUTOSAVE_KEY, JSON.stringify(data))
  } catch {
    // Storage full or unavailable — silently ignore
  }
}

export function loadAutosave(): DiagramJson | null {
  try {
    const raw = localStorage.getItem(AUTOSAVE_KEY)
    if (!raw) return null
    const data = JSON.parse(raw) as DiagramJson
    if (data.version !== 1) return null
    return data
  } catch {
    return null
  }
}

// ============================================================
// JSON file export
// ============================================================

export function exportDiagramJson(
  bubbles: Record<string, Bubble>,
  rails: Record<string, Rail>
): void {
  const data: DiagramJson = {
    version: 1,
    bubbles: Object.values(bubbles),
    rails: Object.values(rails),
  }
  const json = JSON.stringify(data, null, 2)
  const blob = new Blob([json], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = 'factorio-diagram.json'
  a.click()
  URL.revokeObjectURL(url)
}

// ============================================================
// JSON file import
// ============================================================

export function importDiagramJson(): Promise<DiagramJson | null> {
  return new Promise(resolve => {
    const input = document.createElement('input')
    input.type = 'file'
    input.accept = '.json,application/json'
    input.onchange = () => {
      const file = input.files?.[0]
      if (!file) {
        resolve(null)
        return
      }
      const reader = new FileReader()
      reader.onload = () => {
        try {
          const data = JSON.parse(reader.result as string) as DiagramJson
          if (data.version !== 1) {
            resolve(null)
            return
          }
          resolve(data)
        } catch {
          resolve(null)
        }
      }
      reader.readAsText(file)
    }
    input.click()
  })
}
