/**
 * Per-resource-type color palette for rail / feeder / port rendering.
 *
 * Layering (highest priority first):
 *   1. CURATED_OVERRIDES — hand-tuned, high-distinguishability hues for common
 *      items where FactorioLab's muddy average reads poorly as a color code
 *      (and to preserve the ice-cyan / crude-oil-tan the canvas already used).
 *   2. itemColors.json — authentic FactorioLab average-icon color for every
 *      item (896 entries, regenerated by generate-bundled-recipes.mjs). This is
 *      what kills the gray fallback for the long tail of Space Age fluids/items.
 *   3. gray (#808080) — only for genuinely unknown resource names.
 *
 * All three feed a single luminance-lift (`ensureLegible`) so dark/muddy hues
 * stay visible on the near-black canvas. The same display color flows into
 * rails, feeders, input/output tabs, and bubble strokes via getResourceColor.
 */
import { canonicalProductKey } from '../recipes/normalize'
import itemColors from '../recipes/itemColors.json'

const CURATED_OVERRIDES: Record<string, string> = {
  'iron-plate': '#a0a0b0',
  'copper-plate': '#c87941',
  'coal': '#6e6e6e',
  'stone': '#a09070',
  'crude-oil': '#8a6a4a',
  'steel-plate': '#8090a0',
  'copper-cable': '#e08030',
  'iron-gear-wheel': '#909090',
  'stone-brick': '#b09060',
  'pipe': '#a0b0c0',
  'plastic-bar': '#c0b0e0',
  'sulfur': '#d0c050',
  'electronic-circuit': '#60b040',
  'advanced-circuit': '#d04040',
  'processing-unit': '#4060d0',
  'sulfuric-acid': '#b0c030',
  'battery': '#50b0b0',
  'electric-engine-unit': '#9070a0',
  'flying-robot-frame': '#60a0d0',
  'lubricant': '#90c070',
  'logistic-robot': '#d09030',
  'construction-robot': '#40a060',
  'rocket-fuel': '#e07060',
  'solid-fuel': '#c06030',
  'low-density-structure': '#b0a080',
  'rocket-control-unit': '#6080d0',
  'speed-module': '#a030c0',
  // Fulgora / Space Age
  'scrap': '#929292',
  'concrete': '#6a6a72',
  'ice': '#a8d0e0',
  'holmium-ore': '#d08090',
}

/** Canonical-keyed merge: authentic base first, curated overrides win. */
const BASE_COLORS: Record<string, string> = {}
for (const [k, v] of Object.entries(itemColors as Record<string, string>)) {
  BASE_COLORS[canonicalProductKey(k)] = v
}
for (const [k, v] of Object.entries(CURATED_OVERRIDES)) {
  BASE_COLORS[canonicalProductKey(k)] = v
}

/** Raw (un-lifted) hue for a resource — for callers that lift with their own floor. */
function baseColor(resourceType: string): string {
  return BASE_COLORS[canonicalProductKey(resourceType)] ?? '#808080'
}

/**
 * Lift a hex color toward white until it clears a luminance floor, so dark or
 * muddy hues stay legible against the near-black canvas. Colors already above
 * the floor pass through unchanged. Shared by line/fill and label rendering.
 */
function ensureLegible(hex: string, minLum: number): string {
  const m = /^#([0-9a-f]{6})$/i.exec(hex)
  if (!m) return hex
  const n = parseInt(m[1], 16)
  const r = (n >> 16) & 0xff
  const g = (n >> 8) & 0xff
  const b = n & 0xff
  const lum = 0.2126 * r + 0.7152 * g + 0.0722 * b
  if (lum >= minLum) return hex
  const t = (minLum - lum) / 255
  const lift = (c: number) => Math.round(c + (255 - c) * t)
  const hx = (c: number) => c.toString(16).padStart(2, '0')
  return `#${hx(lift(r))}${hx(lift(g))}${hx(lift(b))}`
}

// Lines/fills/strokes: keep hue, just guarantee it reads on dark canvas.
const LINE_MIN_LUM = 96
// Labels sit as small text and need a higher floor than lines.
const LABEL_MIN_LUM = 170

/** Display color for a resource — used by rails, feeders, tabs, bubble strokes. */
export function getResourceColor(resourceType: string): string {
  return ensureLegible(baseColor(resourceType), LINE_MIN_LUM)
}

/** Neutral color for a multi-resource bus (more than one carried type). */
export const BUS_COLOR = '#c0c4d0'

/**
 * Color for a rail: the resource's color when it carries a single type,
 * otherwise a neutral bus color (the label identifies the bus).
 */
export function getRailColor(rail: { resourceTypes: string[] }): string {
  return rail.resourceTypes.length === 1
    ? getResourceColor(rail.resourceTypes[0])
    : BUS_COLOR
}

/**
 * Label color for a rail: the rail's hue lifted to the higher label floor so
 * the name stays readable against the dark canvas.
 */
export function getRailLabelColor(rail: { resourceTypes: string[] }): string {
  const base = rail.resourceTypes.length === 1 ? baseColor(rail.resourceTypes[0]) : BUS_COLOR
  return ensureLegible(base, LABEL_MIN_LUM)
}
